import sqlite3
from typing import List
from dataclasses import asdict
from .data import FileData, HeaderData, TagData


# Helper method - Creates an INSERT statement ready for parameter substitution using the given dict
def insert_dict(table: str, data: dict):
    keys = list(data.keys())
    return f"INSERT INTO {table}({', '.join(keys)}) VALUES (:{', :'.join(keys)})"


# Given metadata generated by mp3qa.extract methods and a database connection,
# load the data into the database (WIHOUT committing changes)
def load(file_data: FileData, header_data: HeaderData, tag_data: List[TagData], con: sqlite3.Connection):
    # INSERT INTO Files ...
    file_query = insert_dict('Files', asdict(file_data))
    con.execute(file_query, asdict(file_data))

    # INSERT INTO Headers_MP3 ... or INSERT INTO Headers_FLAC ...
    header_table = '_'.join(['Headers', file_data.format.upper()])
    header_query = insert_dict(header_table, asdict(header_data))
    con.execute(header_query, asdict(header_data))

    # INSERT INTO Tags ...
    for tag in tag_data:
        tag_query = insert_dict('Tags', asdict(tag))
        con.execute(tag_query, asdict(tag))
